# fly.toml file generated for wouterw-protohackers on 2023-01-28T13:06:58+01:00

app = "wouterw-protohackers"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
ADDR = "0.0.0.0:3000"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = []
    port = 3000

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
